### PR TITLE
More renaming

### PR DESCRIPTION
**Pull request by hannesm**
the `nocrypto_entropy_xen` module is actually not specific to xen, thus I renamed it to `nocrypto_entropy_mirage` (I'm open to naming, maybe `nocrypto_entropy_freestanding` is better (`mirage` can also be run on unix, where the `nocrypto_entropy_lwt` module takes over)?)..  or maybe `nocrypto_entropy_lwt` should be renamed to `nocrypto_entropy`?

In the end, there are now 3 findlib packages dealing with entropy, but there will be no application using more than one of them, thus we can reuse the very same name (and simplify the logic of the `mirage` tool to call `Nocrypto_entropy.initialize ()` at startup).

this is on top of #99 and is best served with https://github.com/mirage/mirage/pull/564

### CODE REVIEW

**Comment by hannesm** [comment]
there is another commit on top of this to add solo5 support to nocrypto: https://github.com/hannesm/ocaml-nocrypto/commit/ee398fc86e59a533fa43283081c68c33aa6c89ee

**Comment by pqwy** [comment]
It's a little more complicated than that. `Entropy_xen` from `mirage-entropy-xen` contains a commented-out [blob of code](https://github.com/mirage/mirage-entropy/blob/master/lib/entropy.ml#L138-L312) that talks to `xentropyd`. That part is rather Xen-specific, because it uses a Xen console for inter-domain communication, and because it uses `xenstored` to locate the console. The occurrences of `xen` in the names there and in `Nocrypto_entropy_xen` reflect the intention to resurrect that code, and get cross-domain entropy injection running in a pretty Xenny way.

On the other hand, the code that is actually doing something has nothing to do with Xen. So I guess that viewing that entropy backend as unrelated to Xen is the easiest thing to do right now, and we can figure out how to reattach `xentropyd` later.

The problem with unifying (what I suppose are) `Nocrypto_entropy_unix`, `Nocrypto_entropy_lwt`, and `Nocrypto_entropy_mirage` is that these have different signatures. `_unix` is not monadic, while `_lwt` makes no reference to an external entropy provider and its abstract types. I'd rather not install three different findlib packages with the same module name but different interfaces and different deps. Of course, it would be worthwhile if we had a way to make the `mirage` tool not even know about `nocrypto`. But as long as it needs to emit the preamble, I prefer to trade in two lines of code there to avoid endless confusion here.

As for the names, all of them are a bit wrong. `_unix` is really `_unix_blocking`, `_lwt` is `_unix_with_lwt`, `_xen` used to be `_mirage_on_xen`, and now `_mirage` means `_mirage_but_for_unikernels`. Other possible names for the last one are `Nocrypto_entropy_unikernel` and `Nocrypto_entropy_internal`, but no user should ever see those in any case.

Lastly, maybe the provider module should not be named `Entropy` as it's still a peculiar form of entropy harvesting. `Unikernel_entropy`, `Internal_entropy`, or `Now_with_more_entropy` spring to mind.

Will merge this, but waiting for input on the last two paragraphs.

**Comment by hannesm** [comment]
Thanks for your extensive reply.

There are two names here: 
 - the module, which is part of nocrypto, and hardcoded in the mirage tool for initialisation.  I'd suggest `Nocrypto_entropy_freestanding` (since mirage is, as you mentioned, misleading).  I don't expect the Nocrypto part to be specific for any concrete freestanding MirageOS backend (Xen/Solo5/..).
 - the module provided by mirage-entropy-*, used by nocrypto.  This used to be `Entropy_xen`, now it is `Entropy`.  I think `Internal_entropy_provider` would be the most appropriate for this module.  The implementation thereof can be different between Xen (using xentropyd) and Solo5 (which might use some virtrnd in the future), but since it is delivered by different opam packages (mirage-entropy-xen / mirage-entropy-solo5), and its interface is the same, there's no need for embedding the `_xen` into its module name.

Does that make sense?  I'll rename in this PR to `Nocrypto_entropy_freestanding` and `Internal_entropy_provider` later.

**Comment by pqwy** [comment]
```
+----------------------------------------------+
| You were killed by the Bikeshedding Express. |
|   [Retry] [Quit]                             |
+----------------------------------------------+
```

I prefer `_mirage`. It's about as freestanding as `unix` is, that is, it depends on an OS-provided entropy driver, and the OS is Mirage in this case. That there's a more direct interface if Mirage is running on Unix is a detail, a bit like the socket-based network stack.

#101 is now in, but with `s/freestanding/mirage/g`. `Nocrypto_entropy_xen` is now `Nocrypto_entropy_mirage`.

The pseudo-library that provides a different compile of stubs is [now separate](https://github.com/mirleft/ocaml-nocrypto/commit/2695a3a7d929df09f4b48e6a3a14f9cc542ce872) from the actual library that deals with the entropy interface. `nocrypto.mirage` contains `Nocrypto_entropy_mirage`; `nocrypto.xen` provides only `dllnocrypto_xen_stubs.so`. Symlinks are not needed, but copying C still is.

https://github.com/hannesm/ocaml-nocrypto/commit/96e81f12341e2ea4b9b492dce539f2445b283ef2 is [in too](https://github.com/mirleft/ocaml-nocrypto/commit/9fe499f9c89caf94ba9718a163cfeb5ba50d796c), with further simplifications. This adds `nocrypto.solo5` with only `dllnocrypto_solo5_stubs.so`.

The Xen part is tested with `mirage-2.9.0`, modified to add `["nocrypto.xen" ; "nocrypto.mirage"]` to `libraries` where appropriate; testing with Solo5 is welcome.

As for the name of the module in `mirage-entropy`, I'm cool with `Entropy`, lest we get hit by the Bikeshedding Express. Just don't rename the file to `Internal_entropy_provider`, I beg of thee.

**Comment by hannesm** [comment]
thanks! (as mentioned on the diff, solo5 support does not work... if life would be that easy)

**Pull request closed without merging**
