### PR TITLE
nuke sexplib/ppx

### PR DESCRIPTION
**Pull request by vbmithr**
Because using ppx is not a good idea, actually.

I'll take my nocrypto without ppx, thank you very much :)

### CODE REVIEW

**Comment by haesbaert** [comment]
Why ? Can you elaborate ?

I actually use and like it.

**Comment by vbmithr** [comment]
With latest version of janestreet software (dev), it makes it hard to compile, and in general, ppx is very dependent of OCaml version being used, at least it was the case until recently.
I suppressed it because I could not compile nocrypto anymore when using janestreet dev libraries.

**Comment by haesbaert** [comment]
That looks like the wrong fix then.

Can't we fix janestreet dev libraries ?
I use sexp on other projects as well, I'd to have to write 582 new
functions for my dhcp library cause we can't use sexp anymore.

**Comment by haesbaert** [comment]
I found the original sexp discussion thread now.

That is depressing. Really depressing.

**Comment by cfcs** [comment]
What is `janestreet software (dev)`? Have they fixed ppx yet?

**Comment by rgrinberg** [comment]
Is this still a problem? I think janestreet fixed this.

**Comment by haesbaert** [comment]
It's all fixed.

**Comment by pqwy** [comment]
I don't particularly like dragging that stuff in either, but it's been used pretty widely. _Some_ uniform external representation is pretty handy, and you probably don't want me to replace sexps with the equivalent ASN.1 😈 .

A birdie told me @dbuenzli has a sexplib-like thing in the pipeline. That's an option.

**Pull request closed without merging**
